### ISSUE TITLE
more axis examples

### ISSUE THREAD

**Issue by ahoyahoy** [mhkeller/layercake#131]
Can you please add some Axis examples with ticks on opposite side (right or top) and chart with more than one axis in one direction?

**Comment by mhkeller** [comment]
For the right or top axes, I have a few other things on my plate at the moment so if you were to start it as a PR that would help. 

I don't think Layer Cake is a great solution for multiple-axis charts since it has a built-in concept of one dataset per `<LayerCake>` component. I would use the `position='absolute'` option to layer multiple `<LayerCake>` components on top of one another but I could also see that being difficult to make room for two axes. I tend to think multiple-axis charts are a difficult design and information challenge so it's not something I've tried to tackle.

**Comment by mhkeller** [comment]
I'm also redoing the existing axis components to make their behavior a bit more standardized

**Comment by mhkeller** [comment]
I'll close this since we're tracking it in this PR: https://github.com/mhkeller/layercake/pull/165

I made some progress this week in a much better AxisY component with an interactive example where you can toggle the different layout options. Now that I have this as a model, I can port it to the other ones.

**Comment by mhkeller** [comment]
Closed via https://github.com/mhkeller/layercake/pull/165
