### ISSUE TITLE
Add ssr={true|false} to control when charts are rendered

### ISSUE THREAD

**Issue by jurb** [mhkeller/layercake#19]
@mhkeller In the docs [you mention](https://layercake.graphics/guide#width):

> The chart will actually render before the container width is measured and you'll get a flash of a chart before it adjusts itself. You can set a default width here that it will render to for that moment. It might be better to just now show the chart during this period but including this option for now. Defaults to 350.

I think this is the culprit of some of my graphs misbehaving with my current setup, depending on the browser I'm using. Do you have a way to not render the chart until after this flash?

**Comment by mhkeller** [comment]
Ya I think having it either 1) only load things once the pages load or 2) load everything with per-determined dimensions is the way to go. It's related to this comment here about server-side rendering and the flash of unsized content not being ideal: https://github.com/mhkeller/layercake/issues/5#issuecomment-581047344

I'll look into the best way to do this. It could be that it just looks for the `window` object. The trick will just be to make sure that it fails gracefully on first load and doesn't error.

**Comment by jurb** [comment]
Cool! Possibly related: if I `console.log($width)` in the chart components, I get 2 results, with the first number being a lot smaller than my container.

**Comment by mhkeller** [comment]
I did some work on this and I think the best solution is to add a prop like `ssr` that defaults to false that turns off all server-side rendering by adding this conditional which is now in the [ssr](https://github.com/mhkeller/layercake/tree/ssr) branch: https://github.com/mhkeller/layercake/blob/734e449a4c5839363f58d489864474dcc3d5a30c/src/LayerCake.svelte#L270-L278

it won't attempt to render any of the elements, which is nice because you won't have to put a bunch of conditional statements in each renderer to check to make sure variables have been calculated. 

I've started building out server-side rendered examples on the [ssr](https://github.com/mhkeller/layercake.graphics/tree/ssr) branch of the website repo and I did an export of the current site with the ssr branch so you can see how it works.

This would also close https://github.com/mhkeller/layercake/issues/5

**Comment by mhkeller** [comment]
@jurb Can you put an example together in the REPL of the charts you say aren't sizing properly?

**Comment by jurb** [comment]
@mhkeller Yes, I'll try to do so this weekend!

**Comment by mhkeller** [comment]
I'll merge this into master when I'm done building out the ssr examples to make sure that it works with all use cases built so far.

**Comment by jurb** [comment]
> @jurb Can you put an example together in the REPL of the charts you say aren't sizing properly?

I'm sorry but I worked on a tight deadline for that project and can't manage to reconstruct the issue in the upcoming time. Once I have time I'll let you know.

Thanks for the great work!

**Comment by mhkeller** [comment]
This is now in 3.0.0 https://github.com/mhkeller/layercake/releases/tag/v3.0.0
