### ISSUE TITLE
Demo request / map overlay question

### ISSUE THREAD

**Issue by jsfenfen** [mhkeller/layercake#20]
Hi, I'm wondering how you'd suggest overlaying bubbles on top of a map layer? It seems like there could be a way to do this with https://layercake.graphics/example/MapLayered but don't immediately see how I would do this for a point layer in unprojected lat/lngs? Would I have to explicitly project them into viewport coordinates? Am not married to it being in canvas or svg, probably either would be fine.  Am looking at tens of bubbles, probably not thousands? If this would need to be a new component, do you have any suggestions on implementation? Thanks in advance.

**Comment by mhkeller** [comment]
Here's an example setting up a second layer and using D3's projection function to do the conversion from lat/lng to the SVG space: https://svelte.dev/repl/3f973c194a1d45079f36e226d4061ef6?version=3.17.3

You could do a more elegant component setup where they share the projection information instead of passing in the projection name as a string but this shows you how to do the core of the conversion.
