### ISSUE TITLE
scaleLog example

### ISSUE THREAD

**Issue by jsfenfen** [mhkeller/layercake#21]
Hey @mhkeller thanks again for handling a steady stream of questions from me... What is the "right" way to set a given axis to a scaleLog? I see scaleLinear and scaleSqrt are set as defaults in [defaultScales.js](https://github.com/mhkeller/layercake/blob/master/src/settings/defaultScales.js) and the scale types seem to be passed to the Axis components as, like, yScale and xScale with getContext('LayerCake'). Does this have to do with the availability of a [nice](https://github.com/mhkeller/layercake/blob/master/src/helpers/createScale.js#L32) function in createScale? Should I be trying to set this in /components/AxisY.svelte ?

**Comment by jsfenfen** [comment]
Hmm, it seems like you can get most of the way there by just making sure the scale doesn't cross zero, I was running into silent errors that went away, mostly, by checking the result of partialDomain are strictly greater than zero. Hmm.

**Comment by mhkeller** [comment]
Hey no worries! You would set it the same way as the examples that use [`scaleBand`](https://layercake.graphics/example/ColumnStacked) or the radar chart [overriding the default](https://layercake.graphics/example/Radar/) `scaleSqrt` to a `scaleLinear`

Here's the relevant part from the [stacked column example](https://layercake.graphics/example/ColumnStacked) that overrides the xScale by setting a `scaleBand`:

```html
<script>
  import { scaleBand } from 'd3-scale';
  // etc...
</script>

<LayerCake
       padding={{ top: 0, right: 0, bottom: 20, left: 20 }}
       x={d => d.data.year}
       y={[0, 1]}
       xScale={scaleBand().paddingInner([0.02]).round(true)}
       xDomain={uniques(fruit, 'year')}
       flatData={flatten(series)}
       data={series}
       custom={{ seriesNames }}
  >
```

I think the sample axis x and y scale renderers should also work since, looking at the scaleLog docs, they seem to have all of the methods that are used. I haven't used a scale log in a while but should add an example. 

I think I should add some example code in [the docs for `xScale`](https://layercake.graphics/guide#xscale) showing this if you think that would help.

**Comment by jsfenfen** [comment]
Awesome, thanks so much @mhkeller that's much cleaner than the awfulness I'm using, if there was an example that would be great. Will take a look this evening. 

It seems that custom axes are needed (I can contribute my YAxis, it's workable) to keep labels from getting printed on each other (e.g., 7,8,9). But I think much of my forehead banging was because I was missing simple mathematical errors from somewhere inside d3-scale.

**Comment by mhkeller** [comment]
Cool. If you have some sample log data, send it my way.

**Comment by mhkeller** [comment]
Here's an example: https://svelte.dev/repl/bb0492fe94284b19a26f731bf4ef2f5e?version=3.17.3

I did spot a small error in the yAxis renderer that made it so that setting the `ticks` prop wouldn't work correctly. It's fixed in this example and I'm updating the other ones

**Comment by jsfenfen** [comment]
Woohoo! 🐪
