### ISSUE TITLE
Piechart

### ISSUE THREAD

**Issue by ranjitindx** [mhkeller/layercake#35]
Help me creating pie chart in layercake

**Comment by mhkeller** [comment]
Hi, I would use D3's arc generators as a starting point. You should be able to adapt a tutorial [like this](https://www.tutorialsteacher.com/d3js/create-pie-chart-using-d3js) or [this](https://www.d3-graph-gallery.com/graph/pie_basic.html). If you look at the [scatter exampe](https://layercake.graphics/example/Scatter) it should be pretty close to that one, instead of plotting circles, you're plotting arc paths.

**Comment by ranjitindx** [comment]
Thankyou
