### ISSUE TITLE
Zoom- and pannable SVG map

### ISSUE THREAD

**Issue by janosh** [mhkeller/layercake#37]
I'm a little new to interactive plotting on the web. If I wanted to plot a zoom- and pannable map of Germany and display some markers on it, could I use `layercake`? I'm guessing I would need to find a Topo/GeoJSON file for Germany and then figure out a way to convert lat/lng coordinates to SVG coordinates? Is layercake the right tool for this?

**Comment by mhkeller** [comment]
Hi @janosh, yes you could do this with LayerCake with the caveat that LayerCake is more like the foundation to such a visualization than it is the actual thing that will plot the map and do that scale transformation.

Take a look at [this SVG map example](https://layercake.graphics/example/MapSvg). It's similar to what you want to do except it doesn't have zooming or panning. Like all of the examples, it uses D3 to convert between the units of the data (in this case lat/lng) and units of the chart (SVG pixel coordinates). The core transformation happens using the [geo-path](https://github.com/d3/d3-geo#geoPath) function and the specified [projection](https://github.com/d3/d3-geo#projections). 

I would take a look at that and also other examples like this one that does [zooming and panning](https://observablehq.com/@d3/zoom-to-bounding-box) – although it may not be exactly what you want since this only zooms to a bonding box. 

Alternatively, you may be able to do what you want with something like [leaflet](https://leafletjs.com/). You can add [a geojson layer](https://leafletjs.com/examples/geojson/) to a basemap and you get the zoom and pan controls for free.

**Comment by janosh** [comment]
Thanks a lot for the quick reply and for explaining some of how this works! I need to do more reading, I think, before taking a crack at this. But it's really cool to see how much you can do these days with JS and a browser!

**Comment by milahu** [comment]
@janosh how is your progress? do you have something copy-paste-able? ; )

**Comment by janosh** [comment]
@milahu Sorry, nothing yet. Had to turn to other things for the time being.

**Comment by mhkeller** [comment]
I haven’t sat down to think about what the best way to do zoom transitions is in a svelte-y way. But I wonder if exposing the svg components as a variable through `let:` would be a useful escape hatch if people wanted to use [the d3 functions](https://github.com/d3/d3-zoom) from within an `onMount`...

The nice thing about LayerCake is that you're not required to use any of the built-in layouts like `<Svg>`. You could just copy the code from LayerCake's source and use a component in your project if you need to customize it, like exposing the `<svg>` or `<g>` element.

**Comment by mhkeller** [comment]
I'm gonna think about if this is the best naming convention for this, but here is how you would change the layout elements to expose the nodes, which you could then hook into using d3.zoom https://github.com/mhkeller/layercake/commit/9350d3f7d6541973af09e7fb19b390bfcadb633f

**Comment by milahu** [comment]
we need `export` and `bind` in this case
with slot props, the value is always undefined in the parent component

<details>

<summary>patch</summary>

```diff
diff --git a/src/layouts/Html.svelte b/src/layouts/Html.svelte
index c164a4a..cae8f2c 100644
--- a/src/layouts/Html.svelte
+++ b/src/layouts/Html.svelte
@@ -1,7 +1,9 @@
 <script>
 	import { getContext } from 'svelte';
 
-	let html;
+	// allow parent component to bind to container element
+	export let html = undefined;
+
 	export let zIndex = undefined;
 	export let pointerEvents = undefined;
 
@@ -19,7 +21,7 @@
 	class="layercake-layout-html"
 	style="top: {$padding.top}px; right:{$padding.right}px; bottom:{$padding.bottom}px; left:{$padding.left}px;{zIndexStyle}{pointerEventsStyle}"
 >
-	<slot {html}></slot>
+	<slot></slot>
 </div>
 
 <style>
diff --git a/src/layouts/ScaledSvg.svelte b/src/layouts/ScaledSvg.svelte
index 5fd09a2..f8bb989 100644
--- a/src/layouts/ScaledSvg.svelte
+++ b/src/layouts/ScaledSvg.svelte
@@ -1,7 +1,9 @@
 <script>
 	import { getContext } from 'svelte';
 
-	let svg;
+	// allow parent component to bind to container element
+	export let svg = undefined;
+
 	export let fixedAspectRatio = 1;
 	export let viewBox = `0 0 100 ${100 / fixedAspectRatio}`;
 	export let zIndex = undefined;
@@ -26,7 +28,7 @@
 		<slot name="defs"></slot>
 	</defs>
 
-	<slot {svg}></slot>
+	<slot></slot>
 </svg>
 
 <style>
diff --git a/src/layouts/Svg.svelte b/src/layouts/Svg.svelte
index c24d629..6bebccf 100644
--- a/src/layouts/Svg.svelte
+++ b/src/layouts/Svg.svelte
@@ -1,8 +1,10 @@
 <script>
 	import { getContext } from 'svelte';
 
-	let svg;
-	let g;
+	// allow parent component to bind to container elements
+	export let svg = undefined;
+	export let g = undefined;
+
 	export let viewBox = undefined;
 	export let zIndex = undefined;
 	export let pointerEvents = undefined;
@@ -27,7 +29,7 @@
 		<slot name="defs"></slot>
 	</defs>
 	<g bind:this={g} class="layercake-layout-svg_g" transform="translate({$padding.left}, {$padding.top})">
-		<slot {svg} {g}></slot>
+		<slot></slot>
 	</g>
 </svg>
 
```

</details>

**Comment by milahu** [comment]
got it working in my toy project [ncs-analyzer](https://milahu.github.io/ncs-analyzer/) with svg-pan-zoom and editable data (#38) 
(the orange curve allows to change the y values)

**Comment by mhkeller** [comment]
Neat. What is in `./svg-pan-zoom/src/svg-pan-zoom.js`?

**Comment by milahu** [comment]
[svg-pan-zoom](https://github.com/ariutta/svg-pan-zoom) @ npm. fixed the sample code. [here](https://github.com/milahu/ncs-analyzer/blob/a8b58394a988f3435f02544747332ecf241b174c/src/App.svelte#L122) is the svg-pan-zoom code in my app

there is a small bug with svg-pan-zoom:
the initial viewBox is not `0 0 100 100` but off by a few numbers, like `2 2 102 102`
so that the `realZoom` value is not 1 but around 1.05

probably i will just test some more zoom-pan libraries until it works ; )
