### ISSUE TITLE
provide write access to data with user-defined setter function

### ISSUE THREAD

**Issue by milahu** [mhkeller/layercake#38]
im trying to make an editable chart, where i can click and drag data points
use case: interactive linear interpolation, similar to [smooth.js](https://github.com/osuushi/Smooth.js) and [jsplinter](https://github.com/frafra/jsplinter)
could be generalized to a svelte svg editor : )

i noticed that the accessor functions are made only for read access

we could extend the existing design like

```js
function accessor(dataPoint, newValue = undefined) {
  if (newValue == undefined) {
    // get
    return dataPoint.x;
  }
  // set
  dataPoint.x = newValue;
  return true; // success
}
```

but for better performance, we should have separate getter and setter functions (unswitching)

the api could look like

```svelte
<LayerCake
  x={p => p.myX}
  xSetter={(p, v) => (p.myX = v)}
>
```

in the trivial case `<LayerCake x={'myX'}>`, layercake can auto-generate a setter function

here is my modified `Scatter.svg.svelte`

<details>

```svelte
<script>
  import { getContext } from 'svelte';

  const { data, xGet, yGet, xScale, yScale } = getContext('LayerCake');

  export let r = 5;
  export let fill = '#000';
  export let stroke = '#0cf';
  export let strokeWidth = 0;
  export let dx = 0;
  export let dy = 0;

  function handleMouseDown(startEvent, dataIndex) {
    const moveMouse = (moveEvent) => {
      // https://github.com/d3/d3-scale#continuous_invert
      $data[dataIndex] = {
        // TODO fix offset. why 25 x 10?
        myX: $xScale.invert(moveEvent.offsetX - 25),
        myY: $yScale.invert(moveEvent.offsetY - 10)
      };
    };
    const stopMove = (stopEvent) => {
      console.log('stop move');
      document.removeEventListener('mousemove', moveMouse);
      document.removeEventListener('mouseup', stopMove);
      //document.removeEventListener('mouseleave', stopMove); // TODO
    };
    document.addEventListener('mouseup', stopMove);
    //document.addEventListener('mouseleave', stopMove); // TODO

    // start moving
    document.addEventListener('mousemove', moveMouse);
  }
</script>

<g class="scatter-group">
  {#each $data as d, dIdx}
    <circle
      cx={$xGet(d) + (typeof dx === 'function' ? dx($xScale) : dx)}
      cy={$yGet(d) + (typeof dy === 'function' ? dy($yScale) : dy)}
      {r}
      {fill}
      {stroke}
      stroke-width={strokeWidth}
      on:mousedown={(event) => handleMouseDown(event, dIdx)}
    />
  {/each}
</g>

<style>
  .scatter-group circle:hover {
    fill: red !important;
  }
</style>
```

</details>

**Comment by mhkeller** [comment]
Very neat. I put your example [into a REPL](https://svelte.dev/repl/f10c3e6f09b842b3bed620cdd74a4e57?version=3.17.3) and did two things:

1. The `-25` and `-10` offsets were coming from the padding. I replaced those hardcoded numbers with `$padding.left` and `$padding.top`.
2. Instead of hardcoding your x and y keys, you can reference the original input props using `$config.x` and `$config.y`. That makes the component more generic and not tied to a specific x and y key setting. Granted, this would only work if the input prop is a string.

I'm wondering whether having a setter in LayerCake would be able to easily trigger Svelte's reactivity and also how it would be able to figure out which data point to change or remove. This example sets the data point by index but it could also work by key. 

This is fairly achievable in user land (and may actually give more options based on the visualization if it's in user land) it may be not be the best candidate to include in the library itself, but if you have an example where it would really be an improvement, that would be great to see.

The scenario that this current example doesn't cover is when you have x and y values that are not described by a simple key string. I think that could be handled this way

```html
<LayerCake
  x={d => d.data[0].myX}
  y={d => d.data[0].myY}
  ...
  custom={{
    setData: (d, xVal, yVal) => {
      d.data[0].myX = xVal;
      d.data[0].myY = yVal;
    }
  }}
>
```

And then in the component inside of mousemove

```js
const newX = $xScale.invert(moveEvent.offsetX - $padding.left);
const newY = $yScale.invert(moveEvent.offsetY - $padding.top);
$data[dataIndex] = $custom.setData($data[dataIndex], newX, newY)
```

That setup frees up the component of any config-specific strings or settings. Let me know what you think and if there is an improvement to be made. My current thinking is this likely belongs in user land but if there's a compelling case that would be super useful to see!

**Comment by milahu** [comment]
> This is fairly achievable in user land

sweet!

demo with custom setter function in [this repl](https://svelte.dev/repl/f5633e357423445ab284b9cf91d3578a?version=3.17.3)

**Comment by mhkeller** [comment]
Fun example! Glad you got it working.
