### ISSUE TITLE
Is there a discussion forum for Layercake ?

### ISSUE THREAD

**Issue by sahuguet** [mhkeller/layercake#48]
I have some naive questions about Layercake and would like to hear feedback about the tools.
Is there a forum (e.g. Discourse) for this?

**Comment by mhkeller** [comment]
Thanks @techniq ! Looking forward to it. I'm updating the website to use svelte kit and I think adding a page for "Components" would be a good addition.

**Comment by mhkeller** [comment]
I just pushed up a "Component gallery" page https://layercake.graphics/components/

I also added jsdoc types to all of the example components, standardized them a bit more and added descriptions for each one. This is brand new so if you see any errors or things that can be improved, let me know.

**Comment by techniq** [comment]
Oh, and I've been working on [svelte-ux](https://github.com/techniq/svelte-ux), which has components, stores (fetch, graphql, query params, local storage, ...), actions, etc.  

The [docs](https://svelte-ux.vercel.app/) are also a WIP as I have about 80-90% of the components documented (mostly just examples, needs descriptions, prop listings, interactive REPLs, etc), but there is a ton to document for the stores and actions.

Anyways, feel free to poke around there as well if you want :).  Things are still in flux as well, but have been used for some production apps.

**Comment by mhkeller** [comment]
Very neat! I like that you have tweens built in the circle element. I feel like that's still an area to have more layer cake examples on – although I don't think there's a good svelte enter-update-exit pattern à la D3 so I'm not sure what a general pattern would be. Let me know when you've finished these!

**Comment by techniq** [comment]
@mhkeller Those tweens are available for `Circle`, `Rect`, and `Line`, and will likely be added for `Path` (using a custom interpolator, and likely [d3-interpolate-path](https://pbeshai.github.io/d3-interpolate-path/) instead of d3's).

`Rect` is great as it is used in `HighlightBar` (likely to be renamed to `HighlightRect`) and gives you smooth tweens for "free".  It's also what enabled the smooth transitions setup on this [REPL](https://svelte.dev/repl/724dc5cc5ec1412d8250439165e123f3?version=3.44.2).  I still need to add these animated examples to the docs, along with the tweened options to coordinate with delays, etc.

Btw I just implemented a solution for Bar group/stack so it supports all the combinations (grouped, stacked, grouped and stacked, separated stack, and percent stacked), which was one of the regressions of my [3c+ experiments](https://svelte.dev/repl/7000c5ce05b84cd98ccbfb2768b4be3d?version=3.44.2) mentioned [here](https://github.com/mhkeller/layercake/issues/29#issuecomment-875904073).

`HighlightLine` uses both `Line` and the `Circle` (for data point(s)) which is run to watch with area stacks :).

Svelte makes all this so much cleaner than it used to be :).

I'll keep you posted.  I'm still painting with pretty broad strokes and need to come up with a good docs pattern.  I'm using mdsvex and preprocess the code examples, but need to do more to build ToC, extract front matter, extra prop tables, etc, and I'd love to have interactive REPLs instead of static pages, especially since the library can not be used on Svelte's REPL at the moment (I think due to the Vite $lib/$app aliases, but not for sure).

**Comment by mhkeller** [comment]
Very neat! Looks like you've been making a lot of progress. Should I close this [issue](https://github.com/mhkeller/layercake/issues/29) since it sounds like you've moved beyond that one?

**Comment by techniq** [comment]
Done :).  I left a note in case someone goes down a similar path.  There might still be an issue with swapping data/flatData within LayerCake,  but my current approach works around this (I think).  I'll know more for certain when I add the more dynamic example in the docs.

Btw, there might be some features in LayerChart worth porting back to LayerCake over time.  For example in my [Chart](https://github.com/techniq/layerchart/blob/master/src/lib/components/Chart.svelte) component it supports `xBaseline` / `yBaseline` props which are useful when want the baseline to be non-zero, or example using `100%` (i.e. `1.0`) like this:

![image](https://user-images.githubusercontent.com/177476/145440945-dc1bcb57-b9d0-40b4-9637-890da093af29.png)

I need to add an example for this as well :).

**Comment by mhkeller** [comment]
Ah neat. Yeah that could be a good addition to the axis components if you want to take a crack at it.

**Comment by techniq** [comment]
@mhkeller Added `tweened` support to Path last night with some docs.  The example is rather fun to play with by stepping the various options / combinations at the top.

I need to add animated axis/grid/scales to being fully animated (on the roadmap, but probably a bit out).  We have this feature in [visx](https://airbnb.io/visx/xychart) with a few options  like "from center", "from outside", "from min", "from max".
