### ISSUE TITLE
LayerCake and SSR?

### ISSUE THREAD

**Issue by zzolo** [mhkeller/layercake#5]
I haven't tried to do it, but it seems like it wouldn't work since LayerCake depends on a DOM element.  Maybe there is some way around this that I don't know about.

**Comment by mhkeller** [comment]
Good question. I haven't played around with using the ssr mode but you're right that it does need that DOM element to measure stuff. Is there a way to know if you're in a server environment? In that case you could accept a default width and height.

I put in the ability to [pass any options](https://github.com/mhkeller/layercake/blob/a5f2ccc25f8d2dd554731f9272a242a4b8a17a35/src/layercake.js#L244) to the `.render` method so you can do `hydrate: true` and that should behave as normal. Let me poke around a bit and also look to what Svelte 3 would do with ssr.

**Comment by mhkeller** [comment]
And if you've done any ssr setups and have an idea let me know!

**Comment by zzolo** [comment]
For reference: [Svelte 3 store proposal](https://github.com/sveltejs/rfcs/blob/7e46f10fa93203066fa0dbd892f44a86ecd220b9/text/0002-reactive-stores.md).

Yeah, I think a component-based approach would be great.  I don't think it would really be all that different, outside usage of course.

The main question, imo, is how to pass the top-level properties around.  It could be done with component properties, or even could be a store as well, though neither is great.  It does sound like this part would be pretty straight-forward in Svelte 3.

**Comment by mhkeller** [comment]
Now with 2.0.0, you get some SSR rendering for free but it's not all the way. Rich has a project that's more thought out support for javascript-less, responsive charts that I think will have some lessons to pull from. But give the new version a whirl and see how it works.

**Comment by mhkeller** [comment]
Here's Rich's SSR technique: https://dev.to/richharris/a-new-technique-for-making-responsive-javascript-free-charts-gmp

The only thing that would have to change to do these kinds of charts with LayerCake is to make a separate Svg layout export that exposes the viewBox settings add `preserveAspectRatio="none"` and adds the non-scaling-stroke CSS which very easy to do.

```css
svg * {
  vector-effect: non-scaling-stroke;
}
```

 It could be called `SvgPercent` or something `SvgScalable`, `SvgPancake` as a reference to Rich's tool. The user would set a manual x and y range of `[0, 100]` so that the scales output in percentages. 

#### Separately

I'm not super into how Layer Cake flashes with the default sized charts currently. You *can* set the default width and height via props but it's always going to be a guessing game and you'll get it wrong for some users. It might be better to have an option that hides the chart (via `visibility: hidden`) until `containerWidth` and `containerHeight` have values. This could be something like

```html
<LayerCake
  hideUntilPageLoads={true}
...
```

which I guess would default to `true`. If you're using the `SvgPancake` option it means you'll have to set that to false but maybe that's fine. Thoughts welcome!

**Comment by mhkeller** [comment]
Defaulting to `false` might be a better choice.

**Comment by mhkeller** [comment]
Hey @zzolo I'm gonna close this one and track it on https://github.com/mhkeller/layercake/issues/19. The ssr branch currently has this feature on it if you want to try it out and I'll merge it once I've tested it with all the existing chart types. Let know if you have any thoughts!
