### ISSUE TITLE
typeerror - calcExtents must be an Array

### ISSUE THREAD

**Issue by mraghuram** [mhkeller/layercake#53]
Hi,

I keep getting this error message that says 'TypeError: The first argument of calcExtents() must be an array.'

However my data I am passing passes the Array.isArray test and is an array of objects

Is there something I am missing?

Murali

**Comment by mhkeller** [comment]
Can you make a repro in the REPL or a GitHub repo?

**Comment by mhkeller** [comment]
@mraghuram please let me know. I'll close this issue if you've moved on.

**Comment by mraghuram** [comment]
hi @mhkeller, sorry I am trying to figure out how to share the information. The data i am using is something I can share on a repl.

I used d3 extent as a work around for now.

**Comment by mhkeller** [comment]
Okay, let me know if there's a way I can take a look somehow. I'll close this for now and feel free to re-open when you are able to share.

**Comment by mhkeller** [comment]
@mraghuram  Here's a link to the REPL where you can log in with GitHub and create a shareable link: https://svelte.dev/repl/hello-world?version=3.44.3

**Comment by tututwo** [comment]
> hi @mhkeller, sorry I am trying to figure out how to share the information. The data i am using is something I can share on a repl.
> 
> I used d3 extent as a work around for now.

Hi @mraghuram, I ran into the same problem just yesterday. You can replicate the same issue by deleting {flatData} in this demo map.
https://layercake.graphics/example/MapSvg

Yesterday I passed in `zDomain`, `zRange` and `z` to _<LayerCake>_ component, but I cant use `zGet` or `zScale` in the descendent component. I guess adding `{flatData}` lets LayerCake's z accessor know extents of the data?(But how? sorry...more question here...)

**Comment by mhkeller** [comment]
@tututwo these are two different issues. The map example needs `flatData` because the value for `data` is a GeoJSON object, not an array, which the `calcExtents` function requires. In order to generate scales, Layer Cake needs an array of objects and accessor functions to know which field to use as each scale's domain.

@mraghuram's issue was different. He said he *was* passing in an array to the `data` prop and still seeing the error. Hope that helps to clarify things. I wonder if renaming `flatData` to something like `dataForExtents` would be more helpful.

**Comment by tututwo** [comment]
Thank you for your explanation! It's clear for me now!

And yes, `dataForExtents` is more intuitive for me, personally.

**Comment by mraghuram** [comment]
@mhkeller sorry about the delay.. Unfortunately, I couldn't share the data. But thanks for closing the issue

**Comment by mhkeller** [comment]
Okay. Try calling `Array.from` around your data to make sure that it is actually an array.
