### ISSUE TITLE
Gradient fill

### ISSUE THREAD

**Issue by PlkMarudny** [mhkeller/layercake#76]
I am trying to define a gradient for the area chart using ```<svelte:fragment>``` to insert the gradient definition  but it does not seem to work -  [REPL](https://svelte.dev/repl/65e41de30f1740c7982a3ccf83b404f8?version=3.48.0) here. In general, I cannot see any example using gradients, is this something unsupported?

**Comment by seblammers** [comment]
I was playing around a bit and just put your gradient definition into the `Area.svelte` instead of your `App.svelte`.

Take a look in this [forked REPL](https://svelte.dev/repl/cb0d220ac7fa4caf8995b2a18d1f31e6?version=3.48.0) to see what that looks like.

**Comment by PlkMarudny** [comment]
Indeed, this works. Thank you very much.

**Comment by mhkeller** [comment]
Hm that is strange. The generated HTML is correct in the first example. I'm not sure why

**Comment by mhkeller** [comment]
The first example works if you add this as the fragment

```
<defs>
	<linearGradient id="myGradient" gradientTransform="rotate(90)">
		<stop offset="20%" stop-color="gold" />
		<stop offset="90%" stop-color="red" />
	</linearGradient>
</defs>
```

This may be a svelte bug. I'll work on another reproduction later without layercake

**Comment by techniq** [comment]
FWIW, I have a gradient component in [LayerChart](https://layerchart.vercel.app/docs/components/LinearGradient) (based on LayerCake) and haven't had this issue myself.

**Comment by mhkeller** [comment]
I haven't dug into this one yet but it was very confusing before. The HTML was being created exactly as you would think it would need to be...

**Comment by mhkeller** [comment]
I'm pretty sure this is the same issue as https://github.com/mhkeller/layercake/issues/97 https://github.com/sveltejs/svelte/issues/7450 https://github.com/sveltejs/svelte/issues/7563

the `linearGradient` element is coming back with a namespace of "http://www.w3.org/1999/xhtml" when it should be "http://www.w3.org/2000/svg".

The fix of putting it inside a `<defs>` element works because svelte is better able to detect that it should be an SVG element... I've been trying to create a svelte-only REPL but I haven't for some reason...

Here's a fix adding the xmlns attr on the `linearGradient` element: https://svelte.dev/repl/66fdfba669cf443382c8d71175900ffc?version=3.55.0

I'll see if I can make a svelte-only version but in the meantime I'll update the docs to talk about gradients with either this or adding the `<defs>` element without the slop directly

**Comment by mhkeller** [comment]
Here's the repro: https://svelte.dev/repl/2647caa253d648428dfd96b8d1d6b974?version=3.55.0

And tracking here: https://github.com/sveltejs/svelte/issues/7807

**Comment by mhkeller** [comment]
This is in the docs: https://github.com/mhkeller/layercake/commit/e459efff16f627507c80364de53d0b22a79884b0
