### ISSUE TITLE
SVG height not calculated properly

### ISSUE THREAD

**Issue by PlkMarudny** [mhkeller/layercake#79]
IF you have a look at the [REPL](https://svelte.dev/repl/0eb41737a2d54f8498d8606bd2b6b22d?version=3.48.0), SVG (with a class ```layercake-layout-svg```) has height set to a value lower than it should be.

![image](https://user-images.githubusercontent.com/4361591/170051971-641bba42-e780-45c8-99b1-06158a0799b3.png)

**Comment by mhkeller** [comment]
I think this is the expected behavior. Looking at your example, the SVG is the exact same size as the enclosing `.chart-container` div. Do you mean you didn't expect your axis labels to overflow? Elements *can* overflow from svg elements, which seems counter-intuitive but is just something that svg allows. Set more bottom padding to move everything up. It looks like 30 or 31 pixels does the job.

**Comment by PlkMarudny** [comment]
That solution works for me, of course. Did not take overflow under
consideration, thank you very much for the helpful hint.

Tomasz Plonka
